### ISSUE TITLE
Syntax errors running the script

### ISSUE THREAD

**Issue by elros28** [haxpor/aseprite-macos-buildsh#2]
I ran the script, but I got the following errors:
[terminal.txt](https://github.com/haxpor/aseprite-macos-buildsh/files/2945633/terminal.txt)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Skipping "%s".' % directory)?
Traceback (most recent call last):
  File "/Users/gabrielballesteros/downloads/deps/depot_tools/gn.py", line 15, in <module>
    import gclient_utils
  File "/Users/gabrielballesteros/Downloads/deps/depot_tools/gclient_utils.py", line 271
    except OSError, e:
                  ^
SyntaxError: invalid syntax
ninja: Entering directory `out/Release'
ninja: fatal: chdir to 'out/Release' - No such file or directory
Note: checking out 'v1.2.10-beta4-93-gcc62e9ed5'.

Besides this, cmake is required (I didn't knew), maybe it should be listed in the pre-requisites.

**Comment by haxpor** [comment]
I'll add cmake as pre-requisites and state in README.md.
I'm not quite sure what's the problem, seem to relate to python stuff. I checked mine via `python -version` and I'm using `2.7.10`. Would you tell me yours? If that's too old, you could try to update python to version I use just to be safe.

**Comment by elros28** [comment]
I checked and I've got python 3.7.1, maybe it's because python 3?
Thanks for the script btw!

**Comment by haxpor** [comment]
I guess it could be, you can try to execute with python version 2.x instead by changing this [line](https://github.com/haxpor/aseprite-macos-buildsh/blob/master/aseprite.sh#L128) to your python 2.x version.

**Comment by Sam1370** [comment]
@elros28 Python 3 requires you to put parentheses around print calls e.g instead of `print "hello"` you do `print ("hello")
